"use client";

import { useState } from "react";
import CommonModal from "@/components/common/Modal/CommonModal";
import CommonButton from "@/components/common/ui/commonButton/CommonButton";
import InputField from "@/components/common/ui/formik/inputField/InputField";
import "../securityModals.scss";

interface VerifyAuthModalProps {
    show: boolean;
    handleClose: () => void;
    onSubmit?: (code: string) => void;
}

export default function VerifyAuthModal({
    show,
    handleClose,
    onSubmit,
}: VerifyAuthModalProps) {
    const [code, setCode] = useState("");

    const handlePaste = async () => {
        try {
            const text = await navigator.clipboard.readText();
            setCode(text.trim().slice(0, 6));
        } catch {
            // clipboard access denied
        }
    };

    return (
        <CommonModal
            show={show}
            handleClose={handleClose}
            heading="Verify Authentication"
            className="security-modal verify-auth-modal"
        >
            <p className="verify-auth-modal__sub">
                Keep a physical or digital copy of your backup code to stay secure.
            </p>

            <InputField
                name="authCode"
                placeholder=""
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                righttext={
                    <span className="verify-auth-modal__paste-btn" onClick={handlePaste}>
                        Paste
                    </span>
                }
                righttextOnclick={handlePaste}
            />

            <p className="verify-auth-modal__hint">
                Enter the 6-digit code generated by the Authentication App.
            </p>

            <CommonButton
                title="Submit"
                className="w-100 security-modal__action-btn mt-3"
                onClick={() => onSubmit?.(code)}
            />
        </CommonModal>
    );
}
